FROM python:3.6
WORKDIR /workspace
COPY . /workspace
RUN pip3 install --upgrade pip
RUN pip3 config set global.index-url https://pypi.doubanio.com/simple
RUN pip3 install -r requirements.txt
ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone