# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import protos.nlp_basic_pb2 as nlp__basic__pb2


class NLPBasicServerStub(object):
  """interface
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.process = channel.unary_unary(
        '/nlp_basic_server.NLPBasicServer/process',
        request_serializer=nlp__basic__pb2.Request.SerializeToString,
        response_deserializer=nlp__basic__pb2.Reply.FromString,
        )


class NLPBasicServerServicer(object):
  """interface
  """

  def process(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_NLPBasicServerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'process': grpc.unary_unary_rpc_method_handler(
          servicer.process,
          request_deserializer=nlp__basic__pb2.Request.FromString,
          response_serializer=nlp__basic__pb2.Reply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'nlp_basic_server.NLPBasicServer', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
